## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_top]							
    set_property IOSTANDARD LVCMOS33 [get_ports clk_top]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_top]
 
## Switches
    set_property PACKAGE_PIN V17 [get_ports switches[0]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[0]]
    set_property PACKAGE_PIN V16 [get_ports switches[1]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[1]]
    set_property PACKAGE_PIN W16 [get_ports switches[2]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[2]]
    set_property PACKAGE_PIN W17 [get_ports switches[3]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[3]]
    set_property PACKAGE_PIN W15 [get_ports switches[4]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[4]]
    set_property PACKAGE_PIN V15 [get_ports switches[5]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[5]]
    set_property PACKAGE_PIN W14 [get_ports switches[6]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[6]]
    set_property PACKAGE_PIN W13 [get_ports switches[7]]                    
        set_property IOSTANDARD LVCMOS33 [get_ports switches[7]]
    set_property PACKAGE_PIN R2 [get_ports reset_top]                    
                set_property IOSTANDARD LVCMOS33 [get_ports reset_top]
	
## LEDs
        set_property PACKAGE_PIN U16 [get_ports leds[0]]                    
            set_property IOSTANDARD LVCMOS33 [get_ports leds[0]]
        set_property PACKAGE_PIN E19 [get_ports leds[1]]                    
           set_property IOSTANDARD LVCMOS33 [get_ports leds[1]]
        set_property PACKAGE_PIN U19 [get_ports leds[2]]                    
            set_property IOSTANDARD LVCMOS33 [get_ports leds[2]]
        set_property PACKAGE_PIN V19 [get_ports leds[3]]                    
            set_property IOSTANDARD LVCMOS33 [get_ports leds[3]]
        set_property PACKAGE_PIN W18 [get_ports leds[4]]                    
            set_property IOSTANDARD LVCMOS33 [get_ports leds[4]]
     
